spring:
  application:
    name: ingredient-client

resilience4j:
  circuitbreaker:
    instances:
      ingredientService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers, circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      all: true