spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KarolBazgier/pizzaHot-config.git
          search-paths: ingredient-service
          clone-on-start: true

server:
  port: 8888