spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KarolBazgier/pizzaHot-config.git
          clone-on-start: true

server:
  port: 8888

encrypt:
  key: s3cr3t
