spring:
  application:
    name: ingredient-client

resilience4j:
  circuitbreaker:
    instances:
      ingredientService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers, circuitbreakerevents,beans,info,threaddump,httptrace,httpexchanges
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      all: true
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0


info:
  contact:
    email: support@pizzacloud.com
    phone: 12-123-21-21


logging:
  level:
    io.github.resilience4j: DEBUG